[project]
name = "miguel-carvajal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MiguelCarvajal", email = "macg4202@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
miguel-carvajal = "miguel_carvajal:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
